spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      authentication-database: admin
      database: mongodb
      port: 27017
      host: localhost
      username: adminUser
      password: root
---
spring:
  profiles:
    active: dev
---
admin:
  key:
    value: "${ADMIN_KEY_VALUE}"
---