dev:
  username: "dev"
  password: "dev"
---
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
---
spring:
  data:
    mongodb:
      database: flueredb
      port: 27017
      host: "localhost"
      username: admin
      password: admin
      authentication-database: admin
---
app:
  property:
    service:
      bootloader-info: true
      security-setup: "demo"
      currency-hardcoded: true