dev:
  username: "dev"
  password: "dev"
---
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
---
#logging:
#  level:
#    ROOT: DEBUG
---
app:
  property:
    service:
      bootloader-info: true
      security-setup: "demo"
      currency-hardcoded: false