spring:
  data:
    mongodb:
      database: flueredb
      port: 27017
      host: "localhost"
      username: admin
      password: admin
      authentication-database: admin
---
spring:
  profiles:
    active: dev
---
admin:
  key:
    value: "${ADMIN_KEY_VALUE}"
---