prod:
  username: "prod"
  password: "prod"
---
spring:
  data:
    mongodb:
      database: flueredb
      port: 27017
      host: "localhost"
      username: admin
      password: admin
      authentication-database: admin
---
currency:
  api:
    key: "${CURRENCY_API_KEY}"
---
app:
  property:
    service:
      bootloader-info: false
      security-setup: "full"
      currency-hardcoded: false
