spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      uri: mongodb://localhost:27017/Budget


jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

