spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      authentication-database: admin
      database: mongodb
      port: 27017
      host: localhost
      username: root
      password: root
---
spring:
  profiles:
    active: dev