spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  data:
    mongodb:
      database: mydatabase
      port: 27017
      host: localhost
#      uri: mongodb://root:root@localhost:27017/mongofluere
#      username: root
#      password: root
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
