dev:
  username: "dev"
  password: "dev"
---
jwt:
  key: "${JWT_KEY}"
---
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
---
admin:
  key:
    value: "${ADMIN_KEY_VALUE}"