services:
  mongo_dev:
    container_name: mongo_dev
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_dev:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: flueredb
  mongo_test:
    container_name: mongo_test
    image: mongo:latest
    ports:
      - "27018:27017"
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: flueredb_test

  mongo-express-dev:
    container_name: mongo-express-dev
    image: mongo-express:latest
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo_dev:27017
      ME_CONFIG_MONGODB_SERVER: mongo_dev
    depends_on:
      - mongo_dev
  mongo-express-test:
    container_name: mongo-express-test
    image: mongo-express:latest
    ports:
      - "8082:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://test:test@mongo_test:27017
      ME_CONFIG_MONGODB_SERVER: mongo_test
    depends_on:
      - mongo_test

volumes:
  mongo_dev:
    driver: local

networks:
  default:
    name: fluere-network

